export const ADD_COMMENT = 'ADD_COMMENT';
export const SET_COMMENTS = 'SET_COMMENTS';
export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const ADD_EMAIL = 'ADD_EMAIL';
export const SET_EMAILS = 'SET_EMAILS';
export const SET_EXCEPTIONS="SET_EXCEPTIONS";
export const SET_SHIPMENTS="SET_SHIPMENTS";
export const SET_INVOICE="SET_INVOICE";
export const FETCH_EXCEPTIONS_START="FETCH_EXCEPTIONS_START";
export const FETCH_EXCEPTIONS_FAILED="FETCH_EXCEPTIONS_FAILED";
export const FETCH_SHIPMENT_INFO="FETCH_SHIPMENT_INFO";
export const FETCH_SHIPMENT_START="FETCH_SHIPMENT_START";
export const FETCH_INVOICE_START="FETCH_INVOICE_START";
export const FETCH_INVOICE_INFO="FETCH_INVOICE_INFO";
export const FETCH_INVOICE_DRILLDOWN_START="FETCH_INVOICE_DRILLDOWN_START";
export const FETCH_INVOICE_DRILLDOWN_DETAILS="FETCH_INVOICE_DRILLDOWN_DETAILS";
export const SET_INVOICE_DRILLDOWN="SET_INVOICE_DRILLDOWN";
export const FETCH_CLIENT_DETAILS_START="FETCH_CLIENT_DETAILS_START";
export const SET_CLIENT_DETAILS="SET_CLIENT_DETAILS";
export const FETCH_CLIENT_DETAILS_FAILED="FETCH_CLIENT_DETAILS_FAILED";
export const FETCH_AR_SUMMARY_START="FETCH_AR_SUMMARY_START";
export const FETCH_AR_SUMMARY_FAILED="FETCH_AR_SUMMARY_FAILED";
export const SET_AR_SUMMARY="SET_AR_SUMMARY";
export const SET_AE_FORM="SET_AE_FORM";




