export const ClientDetails=[
    {
        "id": "CANRIG GROUP",
        "customerGroup": "CANRIG GROUP",
        "balance": "854.33",
        "localBalance": "854.33",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "CANR147IAH",
                "customerGroup": null,
                "balance": "854.33",
                "localBalance": null,
                "customerName": "Canrig Drilling Technology LTD",
                "customerPartyId": "CANR147IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2100372",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "854.33",
                        "customerName": "Canrig Drilling Technology LTD",
                        "customerPartyId": null,
                        "customerId": "C2100372",
                        "currencyCode": "USD",
                        "creditLimitAmount": "1500000",
                        "billingBalance": "854.33",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "DIAMOND OFFSHORE GROUP",
        "customerGroup": "DIAMOND OFFSHORE GROUP",
        "balance": "26162.06",
        "localBalance": "26162.06",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "DIAM154IAH",
                "customerGroup": null,
                "balance": "26162.06",
                "localBalance": null,
                "customerName": "Diamond Offshore Drilling Inc.",
                "customerPartyId": "DIAM154IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2147814",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "26162.06",
                        "customerName": "Diamond Offshore Drilling Inc.",
                        "customerPartyId": null,
                        "customerId": "C2147814",
                        "currencyCode": "USD",
                        "creditLimitAmount": "1300000",
                        "billingBalance": "26162.06",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "DNOW Customer Group",
        "customerGroup": "DNOW Customer Group",
        "balance": "795.85",
        "localBalance": "795.85",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "NATI790IAH",
                "customerGroup": null,
                "balance": "795.85",
                "localBalance": null,
                "customerName": "National Oilwell Varco Distribution HQ",
                "customerPartyId": "NATI790IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2110343",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "795.85",
                        "customerName": "National Oilwell Varco Distribution HQ",
                        "customerPartyId": null,
                        "customerId": "C2110343",
                        "currencyCode": "USD",
                        "creditLimitAmount": "400000",
                        "billingBalance": "795.85",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "Forum Energy Global Group",
        "customerGroup": "Forum Energy Global Group",
        "balance": "299.55",
        "localBalance": "299.55",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "FORUDRIIAH",
                "customerGroup": null,
                "balance": "299.55",
                "localBalance": null,
                "customerName": "Forum US Inc -Drilling",
                "customerPartyId": "FORUDRIIAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2171004",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "299.55",
                        "customerName": "Forum US Inc -Drilling",
                        "customerPartyId": null,
                        "customerId": "C2171004",
                        "currencyCode": "USD",
                        "creditLimitAmount": "100000",
                        "billingBalance": "299.55",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "Halliburton Customer Group",
        "customerGroup": "Halliburton Customer Group",
        "balance": "142108.16",
        "localBalance": "142108.16",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "HALL102IAH",
                "customerGroup": null,
                "balance": "138502.13",
                "localBalance": null,
                "customerName": "Halliburton Energy Services Inc",
                "customerPartyId": "HALL102IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2100672",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "138502.13",
                        "customerName": "Halliburton Energy Services Inc",
                        "customerPartyId": null,
                        "customerId": "C2100672",
                        "currencyCode": "USD",
                        "creditLimitAmount": "12000000",
                        "billingBalance": "138502.13",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            },
            {
                "id": "WELL454IAH",
                "customerGroup": null,
                "balance": "3606.03",
                "localBalance": null,
                "customerName": "Well Dynamics Halliburton",
                "customerPartyId": "WELL454IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2100999",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "3606.03",
                        "customerName": "Well Dynamics Halliburton",
                        "customerPartyId": null,
                        "customerId": "C2100999",
                        "currencyCode": "USD",
                        "creditLimitAmount": "150000",
                        "billingBalance": "3606.03",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "MRC Corporation Group",
        "customerGroup": "MRC Corporation Group",
        "balance": "5777.94",
        "localBalance": "5777.94",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "MRCGDOMIAH",
                "customerGroup": null,
                "balance": "5777.94",
                "localBalance": null,
                "customerName": "MRC Global",
                "customerPartyId": "MRCGDOMIAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2169835",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "5777.94",
                        "customerName": "MRC Global",
                        "customerPartyId": null,
                        "customerId": "C2169835",
                        "currencyCode": "USD",
                        "creditLimitAmount": "300000",
                        "billingBalance": "5777.94",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "NOV Rig Technologies Division",
        "customerGroup": "NOV Rig Technologies Division",
        "balance": "2036",
        "localBalance": "2036",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "NOVR513IAH",
                "customerGroup": null,
                "balance": "2036",
                "localBalance": null,
                "customerName": "NOV Rig Solutions Spares",
                "customerPartyId": "NOVR513IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2151524",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "2036",
                        "customerName": "NOV Rig Solutions Spares",
                        "customerPartyId": null,
                        "customerId": "C2151524",
                        "currencyCode": "USD",
                        "creditLimitAmount": "3000000",
                        "billingBalance": "2036",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "Nabors Group",
        "customerGroup": "Nabors Group",
        "balance": "45131.40",
        "localBalance": "45131.40",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "NABO515IAH",
                "customerGroup": null,
                "balance": "200",
                "localBalance": null,
                "customerName": "Nabors Corporate Services on Behalf of",
                "customerPartyId": "NABO515IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2100506",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "200",
                        "customerName": "Nabors Corporate Services on Behalf of",
                        "customerPartyId": null,
                        "customerId": "C2100506",
                        "currencyCode": "USD",
                        "creditLimitAmount": "100000",
                        "billingBalance": "200",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            },
            {
                "id": "NABOINTIAH",
                "customerGroup": null,
                "balance": "44931.40",
                "localBalance": null,
                "customerName": "Nabors Drilling International Limited",
                "customerPartyId": "NABOINTIAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2100299",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "44931.40",
                        "customerName": "Nabors Drilling International Limited",
                        "customerPartyId": null,
                        "customerId": "C2100299",
                        "currencyCode": "USD",
                        "creditLimitAmount": "3000000",
                        "billingBalance": "44931.40",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "Noble Drilling Group",
        "customerGroup": "Noble Drilling Group",
        "balance": "6470.01",
        "localBalance": "6470.01",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "NOBL131IAH",
                "customerGroup": null,
                "balance": "6470.01",
                "localBalance": null,
                "customerName": "Noble Drilling Services Inc",
                "customerPartyId": "NOBL131IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2143431",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "6470.01",
                        "customerName": "Noble Drilling Services Inc",
                        "customerPartyId": null,
                        "customerId": "C2143431",
                        "currencyCode": "USD",
                        "creditLimitAmount": "1000000",
                        "billingBalance": "6470.01",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "Noble Energy Group",
        "customerGroup": "Noble Energy Group",
        "balance": "7764.26",
        "localBalance": "7764.26",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "NOBL100IAH",
                "customerGroup": null,
                "balance": "7764.26",
                "localBalance": null,
                "customerName": "Noble Energy",
                "customerPartyId": "NOBL100IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2138752",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "7764.26",
                        "customerName": "Noble Energy",
                        "customerPartyId": null,
                        "customerId": "C2138752",
                        "currencyCode": "USD",
                        "creditLimitAmount": "3000000",
                        "billingBalance": "7764.26",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "Omaha Customer Group",
        "customerGroup": "Omaha Customer Group",
        "balance": "2200",
        "localBalance": "2200",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "ELEC112IAH",
                "customerGroup": null,
                "balance": "2200",
                "localBalance": null,
                "customerName": "ELECTION SYSTEMS & SOFTWARE",
                "customerPartyId": "ELEC112IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2145760",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "2200",
                        "customerName": "ELECTION SYSTEMS & SOFTWARE",
                        "customerPartyId": null,
                        "customerId": "C2145760",
                        "currencyCode": "USD",
                        "creditLimitAmount": "125000",
                        "billingBalance": "2200",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "Rowan Customer Group",
        "customerGroup": "Rowan Customer Group",
        "balance": "1219.99",
        "localBalance": "1219.99",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "ROWA280IAH",
                "customerGroup": null,
                "balance": "1219.99",
                "localBalance": null,
                "customerName": "Rowan Companies Inc",
                "customerPartyId": "ROWA280IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2145168",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "1219.99",
                        "customerName": "Rowan Companies Inc",
                        "customerPartyId": null,
                        "customerId": "C2145168",
                        "currencyCode": "USD",
                        "creditLimitAmount": "1500000",
                        "billingBalance": "1219.99",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "SCIENTIFIC DRILLING GROUP",
        "customerGroup": "SCIENTIFIC DRILLING GROUP",
        "balance": "332.15",
        "localBalance": "332.15",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "SCIE110IAH",
                "customerGroup": null,
                "balance": "332.15",
                "localBalance": null,
                "customerName": "Scientific Drilling Houston Technology Center",
                "customerPartyId": "SCIE110IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2154460",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "332.15",
                        "customerName": "Scientific Drilling Houston Technology Center",
                        "customerPartyId": null,
                        "customerId": "C2154460",
                        "currencyCode": "USD",
                        "creditLimitAmount": "100000",
                        "billingBalance": "332.15",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "Vantage Group",
        "customerGroup": "Vantage Group",
        "balance": "992.72",
        "localBalance": "992.72",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "VANT777IAH",
                "customerGroup": null,
                "balance": "992.72",
                "localBalance": null,
                "customerName": "Vantage Drilling",
                "customerPartyId": "VANT777IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2151303",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "992.72",
                        "customerName": "Vantage Drilling",
                        "customerPartyId": null,
                        "customerId": "C2151303",
                        "currencyCode": "USD",
                        "creditLimitAmount": "125000",
                        "billingBalance": "992.72",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    },
    {
        "id": "No Group",
        "customerGroup": "No Group",
        "balance": "23204.12",
        "localBalance": "23204.12",
        "customerName": null,
        "customerPartyId": null,
        "customerId": null,
        "currencyCode": null,
        "creditLimitAmount": null,
        "billingBalance": null,
        "creditLimitPercent": null,
        "pastDueBalance": null,
        "level": 1,
        "clientDetailsList": [
            {
                "id": "ALABPOBIAH",
                "customerGroup": null,
                "balance": "5916.23",
                "localBalance": null,
                "customerName": "Al Abdulkarim Holding Company",
                "customerPartyId": "ALABPOBIAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2100610",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "5916.23",
                        "customerName": "Al Abdulkarim Holding Company",
                        "customerPartyId": null,
                        "customerId": "C2100610",
                        "currencyCode": "USD",
                        "creditLimitAmount": "170000",
                        "billingBalance": "5916.23",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            },
            {
                "id": "CONA502IAH",
                "customerGroup": null,
                "balance": "1960",
                "localBalance": null,
                "customerName": "Conagra Foods, Inc.",
                "customerPartyId": "CONA502IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2145674",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "1960",
                        "customerName": "Conagra Foods, Inc.",
                        "customerPartyId": null,
                        "customerId": "C2145674",
                        "currencyCode": "USD",
                        "creditLimitAmount": "200000",
                        "billingBalance": "1960",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            },
            {
                "id": "HARR124IAH",
                "customerGroup": null,
                "balance": "8400",
                "localBalance": null,
                "customerName": "Harris Florida Acquisitions",
                "customerPartyId": "HARR124IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2159596",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "8400",
                        "customerName": "Harris Florida Acquisitions",
                        "customerPartyId": null,
                        "customerId": "C2159596",
                        "currencyCode": "USD",
                        "creditLimitAmount": "4200",
                        "billingBalance": "8400",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            },
            {
                "id": "MEAR450IAH",
                "customerGroup": null,
                "balance": "1100",
                "localBalance": null,
                "customerName": "MEARS GROUP, INC.",
                "customerPartyId": "MEAR450IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2152682",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "1100",
                        "customerName": "MEARS GROUP, INC.",
                        "customerPartyId": null,
                        "customerId": "C2152682",
                        "currencyCode": "USD",
                        "creditLimitAmount": "3000",
                        "billingBalance": "1100",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            },
            {
                "id": "SAUD280IAH",
                "customerGroup": null,
                "balance": "1437.30",
                "localBalance": null,
                "customerName": "SAUDI ARAMCO ROWAN OFFSHORE DRILLING CO.,",
                "customerPartyId": "SAUD280IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2166595",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "1437.30",
                        "customerName": "SAUDI ARAMCO ROWAN OFFSHORE DRILLING CO.,",
                        "customerPartyId": null,
                        "customerId": "C2166595",
                        "currencyCode": "USD",
                        "creditLimitAmount": "350000",
                        "billingBalance": "1437.30",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            },
            {
                "id": "TETR249IAH",
                "customerGroup": null,
                "balance": "285.26",
                "localBalance": null,
                "customerName": "Tetra Technologies Inc",
                "customerPartyId": "TETR249IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2102320",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "285.26",
                        "customerName": "Tetra Technologies Inc",
                        "customerPartyId": null,
                        "customerId": "C2102320",
                        "currencyCode": "USD",
                        "creditLimitAmount": "50000",
                        "billingBalance": "285.26",
                        "creditLimitPercent": null,
                        "pastDueBalance": "0",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            },
            {
                "id": "UNIT233IAH",
                "customerGroup": null,
                "balance": "4105.33",
                "localBalance": null,
                "customerName": "United Airlines Inc.",
                "customerPartyId": "UNIT233IAH",
                "customerId": null,
                "currencyCode": null,
                "creditLimitAmount": null,
                "billingBalance": null,
                "creditLimitPercent": null,
                "pastDueBalance": null,
                "level": 2,
                "clientDetailsList": [
                    {
                        "id": "C2149744",
                        "customerGroup": null,
                        "balance": null,
                        "localBalance": "4105.33",
                        "customerName": "United Airlines Inc.",
                        "customerPartyId": null,
                        "customerId": "C2149744",
                        "currencyCode": "USD",
                        "creditLimitAmount": "1000000",
                        "billingBalance": "4105.33",
                        "creditLimitPercent": null,
                        "pastDueBalance": "708.07",
                        "level": 0,
                        "clientDetailsList": null
                    }
                ]
            }
        ]
    }
]